### PR TITLE
Compat ckeditor 3.2

### PR DESCRIPTION
**Pull request by jrief**
This PR adds support for django-CMS-3.4 and djangocms-text-ckeditor-3.1 and higher.
When merged it will trigger a version jumpt to 0.12.0.

@pcolmant please review it, since it is going to superseed your PR #210.

### CODE REVIEW

**Comment by pcolmant** [comment]
Thanks a lot Jacob,

It works fine. I have not tested the "TODO: need to be re-tested" in the migration. I'll do it tomorrow, because it's late.

I hope that the #212 or similar will be included in the 0.12.0 release ;-)

**Comment by pcolmant** [comment]
In to TODO, is the regex correct ? : ]*)\bid="plugin_obj_(?P<pk>\d+)"([^>]*)/?>
Shouldn't it be : ]*)\bid="plugin_obj_(?P<pk>\d+)"([^>]*)\/?>

So with a \ before the final /?>

**Comment by jrief** [comment]
To be honest, I just copy & pasted it from the migration from cms-text-ckeditor without looking at it too much.

However, I believe the regex is correct. The backslash to escape would even be harmful, because the regex-string starts with a ``r"`` for raw, indicating that escaping is not desired.

**Comment by pcolmant** [comment]
Thanks. 
So that is seems me clearer. 
Maybe I need to make tests with more versions of "cms cascade" and "ck editor", but for me actually the 'false' can be removed because the user has always control of what he wants, even after the migration.

**Pull request merged**
