### PR TITLE
Add a missing migration

### PR DESCRIPTION
**Pull request by rfleschenberg**
I hope that, together with the recent app_label changes, this finally fixes the whole migrations issue.

However, we should probably give this some more thought, especially with regards to backwards compatibility. I totally do not know how this will behave on existing installations.

I am also a little confused about why Django wants to delete all these models. So, please review this.

I can probably do some testing with an existing project this weekend.

### CODE REVIEW

**Comment by jrief** [comment]
@rfleschenberg please rename the file to something appropriate, ``0007_auto_...`` is not an self explaining name.

**Comment by rfleschenberg** [comment]
Ok. It's the name generated by makemigrations :) Do you have a suggestion for a better name? Also, is deleting all these models ok from your point of view?

**Comment by rfleschenberg** [comment]
To be honest, I suspect that something is not quite right here. Maybe the recent app_label changes broke something, and we did not realize it yet?

**Comment by rfleschenberg** [comment]
The problem is that Django only sees the models for those plugins that are activated via `CMSPLUGIN_CASCADE_PLUGINS`. I generated this migration with a project where that setting was empty, so `makemigrations` wants to delete all the models. If I use a project with this setting, `makemigrations` doesn't generate any migrations:

```
CMSPLUGIN_CASCADE_PLUGINS = [
    'cmsplugin_cascade.bootstrap3',
    'cmsplugin_cascade.bootstrap3.secondary_menu',
]
```

@jrief , do you know why secondary_menu is special here? If I don't list it, I get a delete migration for it.

As of now, I think we ship migrations for all our plugins. This is the right thing to do, IMHO. So we should discard this PR.

The drawback of the current approach is that users get tables for plugins they do not use. But that is the lesser evil, compared to shipping an app with incomplete migrations.

Another approach would be to use one Django app per plugin. This would require a data migration for existing installations.

The good thing about discarding this PR is that we do not have to come up with a name for the migration ;)

**Comment by rfleschenberg** [comment]
Oh, wait, I forgot something: If users define `CMSPLUGIN_CASCADE_PLUGINS` differently in their project, they *will* a migration inside Cascade.

Should we maybe force Cascade to always make all models visible to Django?

**Comment by rfleschenberg** [comment]
I think we can close this as outdated.

**Pull request closed without merging**
