### PR TITLE
Fieldsets nested with django-entangled

### PR DESCRIPTION
**Pull request by haricot**
Related:  https://github.com/jrief/djangocms-cascade/issues/358 https://github.com/jrief/django-entangled/pull/3
The test passes here: https://travis-ci.org/haricot/djangocms-cascade/builds/615499744
When the modal is not maximizing the forms displays as before.
I also had to modify the sytles of the breackpoints a little so that they display closer to their checkboxes when they are maximzed. They display a little differently when they are not maximized, but this can be remedied if needed.

Capture d’écran du 2019-11-22 12-17-27
Capture d’écran du 2019-11-22 12-16-59

### CODE REVIEW

**Comment by jrief** [comment]
I'm not that convinced, that this is a good approach. Until Cascade<1.0 indeed, many multi-widgets extended over a single row. Now they extend vertically. This in my opinion is quite useful for editors working with narrow screens.

Look at this example, the window size is 1280 pixels which is quite large:

Screen Shot 2019-11-24 at 10 42 49

It simply would be impossible to render all those select fields in one row, unless you have an ultra-wide screen. And wrapping is even more ugly.

Your pull request however made me think about the labels inside the select fields. If we proceed with your proposal, then labeling them "Inherit from above" doesn't make sense. Having "Inherit from left" also seems inappropriate. I therefore relabled them to "Inherit from <previous breakpoint>". This at least makes the arrangement of fields independent, at the cost that now they even got wider.

I'm interested about your opinion.

**Comment by haricot** [comment]
I think once the concept of breakpoints acquired, texts are superfluous in view of recurrence.
I prepare a screenshot in this direction with pure texts. to support a specific global help (?)

**Comment by haricot** [comment]
My preference is ergonomics because they are fields that come back very often.
With this approach, most fields can appear in the small windows of the modal with the help of hovering if necessary.

Capture d’écran du 2019-11-24 13-50-23

**Comment by jrief** [comment]
hmm, probably you are right.
But then tooltips are mandatory.
I also would add the width in pixels inside the help-text below the label.

**Comment by haricot** [comment]
Great ! I will prepare that. I will first make the PR for # 362 "CascadeUtilitiesMixin accept css_classes or htmt_attribute" because this could be more efficient than the fields_property_in_nested_lists function I added.

**Comment by haricot** [comment]
PR transferted to #365

**Pull request closed without merging**
