### PR TITLE
Corrects undo/redo

### PR DESCRIPTION
**Pull request by haricot**
By testing a little deeper, I realized that I had forgotten a lot of changes.
With these last ones, there would be no error message, all the plugins work correctly except the undo when there is a panel in accordion, the panel-type does not return without causing error.

I make a lot of unique commit, after reflection I would not have to proceed as well.

Apparently PR [djangocms-history#21](https://github.com/divio/djangocms-history/pull/21) is not necessary modification for the future djangocms-cascade version. And maybe custom operations and actions [djangocms_history/models.py#L35](https://github.com/haricot/djangocms-history/blob/fe2ffc424a584cc71b0bfa9c22d55087644bad02/djangocms_history/models.py#L35) is better for cascade.

I hope not to waste your time.

### CODE REVIEW

**Comment by jrief** [comment]
Thanks for your pull request.
There is something I do not  understand, how can the `glossary` become a string, why do you check for it? This field should never be anything but a dict.

**Comment by haricot** [comment]
i do not know too much but djangocms-history seems to turn that into json
[djangocms_history/models.py#L31](https://github.com/divio/djangocms-history/blob/5908350b613015717ba3f607fee462cb06213f88/djangocms_history/models.py#L31)

it is possible that it is a bug, there may be a custom operations and actions on djangocms-history that will be better maybe.

**Comment by jrief** [comment]
is this PR ready for merging?

**Comment by haricot** [comment]
I'm not sure, I'm checking, but all that will be maybe a bug cited [djangocms-history#20](https://github.com/divio/djangocms-history/issues/20) (Error when undoing changes on a JSONField (escaped quotes in result))

**Comment by haricot** [comment]
related https://github.com/jrief/djangocms-cascade/pull/281

**Pull request closed without merging**
