### PR TITLE
Fix gutter Jumbotron if first child is Row

### PR DESCRIPTION
**Pull request by haricot**
With BootstrapJumbotronPlugin add gutter if first child plugin is BootstrapRowPlugin.
We could do that with css or scss  too.

### CODE REVIEW

**Comment by haricot** [comment]
We can add a row directly to a Jumbotron but scrolling padding seems incorrect, we must correct it I think, if not do not allow it.

**Comment by jrief** [comment]
Just to understand the problem, could you please create a demo on https://codepen.io/
I used that tool a lot to test the migration for Bootstrap-4.

**Comment by haricot** [comment]
The combo Jumbotron/row Plugin simplifies the number of plugins to see  background image en container on when there is a lot.
As you said maybe we need to create an `BootstrapUtilities` type for that

Here to not allow Jumbotron/row PLugin:
```    
parent_classes = ['BootstrapContainerPlugin', 'BootstrapColumnPlugin']
```

https://github.com/jrief/djangocms-cascade/blob/ca2c089f5dd74bcdf37263a17950532ac25d0e7f/cmsplugin_cascade/bootstrap4/container.py#L138

**Comment by haricot** [comment]
Also with jumbotron/row/image  this error appears.
```
djangocms-cascade/cmsplugin_cascade/bootstrap4/container.py", line 130, in get_grid_instance
    container = self.get_ancestors().order_by('depth').filter(query).last().get_bound_plugin().get_grid_instance()
AttributeError: 'NoneType' object has no attribute 'get_bound_plugin'
```

**Pull request merged**
