### PR TITLE
Update utils.py

### PR DESCRIPTION
**Pull request by khrizo**
Fix media queries for background images in jumbotron plugin.

### CODE REVIEW

**Comment by jrief** [comment]
Please also adopt to unit testing code. Thanks.

**Comment by khrizo** [comment]
J - Thanks for taking the time to take care of it.

**Comment by jrief** [comment]
@khrizo Today I ran into the problem, that the new media queries you proposed, do not work with the ``<picture>``-element.
Could you please experiment with other settings, otherwise I have to revert your pull request.

**Comment by khrizo** [comment]
Will work on it tonight.

**Comment by jrief** [comment]
I forgot to mention, that I always work with Chrome

**Comment by khrizo** [comment]
@jrief 

Take a look, left Chrome, Safari on the right (Same case with the iPhone). I have uploaded a static page here http://dev.next-workspaces.com/demo/index.html

I haven’t tested these with any other element from cascade, only made the changes to jumbotron.

**Comment by jrief** [comment]
no it works! Weird somehow that yesterday, I had problems with that settings.

**Pull request closed without merging**
