### PR TITLE
WIP Cascade compact ui: admin form

### PR DESCRIPTION
**Pull request by haricot**
Needed to merged before:
https://github.com/jrief/django-entangled/pull/3
https://github.com/jrief/djangocms-cascade/pull/363

### CODE REVIEW

**Comment by haricot** [comment]
In this proposal, the Cascade compact admin form can be displayed in very small window.
The widget selection options (operating system) are replaced by the input list options, allowing you to see as many options in the visible space without scrolling and this makes it easy to add icons . 
The cascading font icon corresponds to the name value bootstrap and the automatic import of the correct icon.The design of the icons are not very important as far as they are different.
The fieldbox are defined in parentheses or list and fields are tweak in the fieldset.
This widget uses cascading style sheets for interaction, I envisioned a javascript version if needed.
This compact design may be optional during configuration.

Screenshot_2019-12-03 Change bootstrap column plugin model Django site admin

**Comment by haricot** [comment]
Input select CSS in action:

Peek 03-12-2019 12-12

**Comment by jrief** [comment]
This layout look really cool!
Does it need your pull request on entangled fields?

I'm currently implementing the possibility to nest EntangledForms inside other EntangledForms.

**Comment by haricot** [comment]
Yes that use my PR entangled for this, proceeded  like this :
```
        glossary_fields = ((list(width_fields.keys()), list(offset_fields.keys()),list(reorder_fields.keys()),\
                           list(responsive_fields.keys())))
 
        class Meta:
            entangled_fields = {'glossary': glossary_fields}
            entangled_field_subsets=(
(None , { 'description': '<div><b>Column</b><i class="icon-col-title"> </i></div> <label for="help"><input type="checkbox" id="help" name="help" > Help</label>' , 'classes': ( 'cascade_horizontal',), "fields" : (list(width_fields.keys()))}),
(None , { 'description': '<div><b>Offset</b><i class="icon-offset-title"> </i></div> <label for="help"><input type="checkbox" id="help" name="help" > Help</label>' , 'classes': ( 'cascade_horizontal'), "fields" :  (list(offset_fields.keys())) }),
(None , { 'description': '<div><b>Order</b> <i class="icon-order-title"></i> </div> <label for="help"><input type="checkbox" id="help" name="help" > Help</label>' , 'classes': ( 'cascade_horizontal'), "fields" :  (list(reorder_fields.keys())) }),
(None , { 'description': '<div><b>Visible</b><i class="icon-visible-title"></i> </div> <label for="help"><input type="checkbox" id="help" name="help" > Help</label>' , 'classes': ( 'cascade_horizontal'), "fields" :  ( list(responsive_fields.keys())) })
            )
```
Good news for feature possibility to nest EntangledForms inside other EntangledForms.

**Comment by haricot** [comment]
I'm glad you like the compact interface, and thank you very much for the django-entangled branch develop.
For information, I started a branch https://github.com/jrief/djangocms-cascade/compare/master...haricot:nested_entangled_ui,
I encountered a problem with the translations in the file  https://github.com/haricot/djangocms-cascade/blob/nested_entangled_ui/cmsplugin_cascade/bootstrap4/mixins.py which I have dodged for the moment.
Also I haven't been able to work the form validations yet.
However, it works well apart from that. I can now add the following, hoping that this is appropriate.

**Comment by haricot** [comment]
Closed in flavor https://github.com/jrief/djangocms-cascade/pull/368

**Pull request closed without merging**
