### PR TITLE
Ability to allow all possible plugins

### PR DESCRIPTION
**Pull request by maxvyaznikov**
Ability to allow all possible plugins throw:
CMS_CASCADE_LEAF_PLUGINS = []

### CODE REVIEW

**Comment by narayanaditya95** [comment]
@jrief May I continue working on this PR? I will have @maxvyaznikov 's commit included as it is. We can reset the upstream merge and instead have a rebase against the upstream. I will probably have to open up a new PR for the same. @maxvyaznikov Is that fine with you?

**Comment by maxvyaznikov** [comment]
All is fine. Do what you want

**Comment by narayanaditya95** [comment]
@maxvyaznikov Thank you.

**Comment by rfleschenberg** [comment]
Is this feature still something that people want? If so, we should take a new look at it. We would also need documentation for this. Please provide some feedback about wether this is still an issue for you.

If there is no user demand for this at the moment, we will close it at some point.

Thanks everyone!

**Comment by rfleschenberg** [comment]
Closing since there has been no feedback for 4 months. Thanks, everyone!

**Pull request closed without merging**
