### PR TITLE
Add a missing migration

### LINKED ISSUE #218: missing migration for iconfont.identifier and icon font.zip_file
We're getting a missing migration for identifier and zip_file fields of the iconfont model.

$ pip freeze | grep cascade
djangocms-cascade==0.11.2

```
$ more ~/.virtualenvs/shop-core/lib/python2.7/site-packages/cmsplugin_cascade/migrations/0015_auto_20170111_1300.py
# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_cascade', '0014_glossary_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconfont',
            name='identifier',
            field=models.CharField(help_text='A unique identifier to distinguish this icon font.', max_length=50, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='iconfont',
            name='zip_file',
            field=filer.fields.file.FilerFileField(help_text='Upload a zip file created on <a href="http://fontello.com/" target="_blank">Fontello</a> containing fonts.', on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
        ),
    ]
```

### PR DESCRIPTION
**Pull request by rfleschenberg**
Fixes #218

### CODE REVIEW

**Comment by rfleschenberg** [comment]
I'm not merging this myself, because a second pair of eyes is always good :) @jrief @Arany, please merge if you're ok with it.

**Comment by rfleschenberg** [comment]
I just merged #221 which will break the build until this one is merged ;)

**Comment by electroniceagle** [comment]
shouldn't this be merged and closed?

**Comment by rfleschenberg** [comment]
@jrief ping

**Pull request closed without merging**
